In [1]:
# All Includes

import random
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from tensorflow import keras
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score
import pandas as pd
import os

In [2]:
piece_1 = []
piece_t1 = []
for i in [1,2]:
    for j in range(1,25):
        train_x = pd.read_csv('./A_DeviceMotion_data/dws_{}/sub_{}.csv'.format(i,j))
        test_x = pd.read_csv('./A_DeviceMotion_data/dws_11/sub_{}.csv'.format(j))
        piece_t1.append(test_x)
        piece_1.append(train_x)

for i in range(48):
    del piece_1[i]['Unnamed: 0']
    piece_1[i]['res'] = 0
for i  in range(24):
    del piece_t1[i]['Unnamed: 0']
    piece_t1[i]['res'] = 0
    
piece_2 = []
piece_t2 = []
for i in [9]:
    for j in range(1,25):
        train_x = pd.read_csv('./A_DeviceMotion_data/jog_{}/sub_{}.csv'.format(i,j))
        test_x = pd.read_csv('./A_DeviceMotion_data/jog_16/sub_{}.csv'.format(j))
        piece_t2.append(test_x)
        piece_2.append(train_x)
        
for i in range(24):
    del piece_2[i]['Unnamed: 0']
    piece_2[i]['res'] = 1
    del piece_t2[i]['Unnamed: 0']
    piece_t2[i]['res'] = 1
    
piece_3 = []
piece_t3 = []
for i in [5]:
    for j in range(1,25):
        train_x = pd.read_csv('./A_DeviceMotion_data/sit_{}/sub_{}.csv'.format(i,j))
        test_x = pd.read_csv('./A_DeviceMotion_data/sit_13/sub_{}.csv'.format(j))
        piece_3.append(train_x)
        piece_t3.append(test_x)
        
for i in range(24):
    del piece_3[i]['Unnamed: 0']
    piece_3[i]['res'] = 2
    del piece_t3[i]['Unnamed: 0']
    piece_t3[i]['res'] = 2

DATA = piece_1+piece_2+piece_3

test_DATA = piece_t1+piece_t2+piece_t3

random.shuffle(DATA)
random.shuffle(test_DATA)

#sc=MinMaxScaler()

val_x = []
val_y = []
data_x = []
T_data_x = []
data_y = []
T_data_y = []
#print(DATA[0].iloc[:,0:12].values)
for i in range(72):
    data_x.append(DATA[i].iloc[:,0:12].values)
    data_y.append(DATA[i].iloc[:,-1].values)
for i in range(24):
    val_x.append(DATA[i+72].iloc[:,0:12].values)
    val_y.append(DATA[i+72].iloc[:,-1].values)
for i in range(72):
    T_data_x.append(test_DATA[i].iloc[:,0:12].values)
    T_data_y.append(test_DATA[i].iloc[:,-1].values)

#print(data_x[0][0])

x_val = keras.preprocessing.sequence.pad_sequences(val_x, maxlen=3000, padding='post', dtype='float32')
y_val = keras.preprocessing.sequence.pad_sequences(val_y, maxlen=1, padding='post', dtype='float32')
x_train = keras.preprocessing.sequence.pad_sequences(data_x, maxlen=3000, padding='post', dtype='float32')
y_train = keras.preprocessing.sequence.pad_sequences(data_y, maxlen=1, padding='post', dtype='float32')
x_test = keras.preprocessing.sequence.pad_sequences(T_data_x, maxlen=3000, padding='post', dtype='float32')
y_test = keras.preprocessing.sequence.pad_sequences(T_data_y, maxlen=1, padding='post', dtype='float32')

print(x_train.shape)
#data["train_x"] = np.array(data_x)
#print(data["train_x"].shape)
#data["train_y"] = np.array(y_train)

#encoded =[]
encoded= keras.utils.to_categorical(y_train,num_classes=3, dtype='float32')
T_encoded = keras.utils.to_categorical(y_test,num_classes=3, dtype='float32')
val_encoded = keras.utils.to_categorical(y_val,num_classes=3, dtype='float32')   

#print(data["train_x"].shape)
print(encoded.shape)
print(T_encoded)

(72, 3000, 12)
(72, 3)
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [3]:
model = keras.models.Sequential()
for i in range(2):
    model.add(keras.layers.LSTM(128, batch_input_shape=(24, 3000, 12), stateful=True, return_sequences=True,kernel_regularizer=keras.regularizers.l2(0.01)))
    model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.LSTM(128, batch_input_shape=(None, 3000, 12), stateful=True))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(3, activation='softmax'))

#model = keras.models.Sequential() # Sequeatial Model 
#model.add(keras.layers.LSTM(128, input_shape=(3000, 12),kernel_regularizer=keras.regularizers.l2(0.01))) # (timestep, feature) 
#model.add(keras.layers.Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (24, 3000, 128)           72192     
_________________________________________________________________
dropout (Dropout)            (24, 3000, 128)           0         
_________________________________________________________________
lstm_1 (LSTM)                (24, 3000, 128)           131584    
_________________________________________________________________
dropout_1 (Dropout)          (24, 3000, 128)           0         
_________________________________________________________________
lstm_2 (LSTM)                (24, 128)                 131584    
_________________________________________________________________
dropout_2 (Dropout)  

In [4]:
def create_callbacks():
    tensorboard_callback = keras.callbacks.TensorBoard(log_dir=os.path.join(os.getcwd(), "tb_log", "5h_adam_20epochs"), histogram_freq=1, batch_size=32,
                                       write_graph=True, write_grads=False)
    

    return [tensorboard_callback]

In [5]:
callbacks = create_callbacks()
el=keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=0, verbose=0, mode='auto')
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=os.path.join(os.getcwd(), "tb_log", "5h_adam_20epochs"), histogram_freq=1, batch_size=32,
                                       write_graph=True, write_grads=False)
model.fit(x=x_train, y=encoded,
          validation_data=(x_val,val_encoded),
          epochs=30,
          callbacks=[el,tensorboard_callback])

        
model.save('./model/LSTM.h5')

Train on 72 samples, validate on 24 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/30
72/72 [==============================] - 27s 373ms/sample - loss: 3.3242 - acc: 0.3611 - val_loss: 3.1738 - val_acc: 0.9167
Epoch 2/30
72/72 [==============================] - 27s 374ms/sample - loss: 3.0993 - acc: 0.8056 - val_loss: 2.9600 - val_acc: 0.9583
Epoch 3/30
72/72 [==============================] - 28s 385ms/sample - loss: 2.8775 - acc: 0.7917 - val_loss: 2.7331 - val_acc: 0.9583
Epoch 4/30
72/72 [==============================] - 28s 386ms/sample - loss: 2.6484 - acc: 0.7917 - val_loss: 2.4706 - val_acc: 0.9583
Epoch 5/30
72/72 [==============================] - 28s 390ms/sample - loss: 2.3942 - acc: 0.8611 - val_loss: 2.2010 - val_acc: 0.9583
Epoch 6/30
72/72 [==============================] - 28s 390ms/sample - loss: 2.0904 - acc: 0.9167 - val_loss: 1.8993 - val_acc: 0.9583
Epoch 7/30
72/72 [==============================] - 28s 392ms/sample - loss: 1.8621 - acc: 0.9028 

In [6]:
results = model.evaluate(x_test, T_encoded)

72/72 [==============================] - 10s 136ms/sample - loss: 3.2275 - acc: 0.7222
